# Generated by Django 3.1.4 on 2021-01-02 09:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
        ('company', '0003_auto_20210102_0715'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, verbose_name='código')),
                ('name', models.CharField(max_length=70, verbose_name='nombre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'tipo de documento',
                'verbose_name_plural': 'tipos de documentos',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='número')),
                ('person_name', models.CharField(blank=True, max_length=100, verbose_name='nombre de la persona')),
                ('note', models.CharField(max_length=500, verbose_name='nota')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='importe')),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='descuento')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='impuesto')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=32, verbose_name='total')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('doctype', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='document.documenttype', verbose_name='tipo')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='person.person')),
            ],
            options={
                'verbose_name': 'documento',
                'verbose_name_plural': 'documentos',
            },
        ),
        migrations.AddConstraint(
            model_name='documenttype',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_documenttype'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('doctype', 'number'), name='unique_doctype_number'),
        ),
    ]
