# Generated by Django 3.1.4 on 2021-01-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='importe'),
        ),
        migrations.AlterField(
            model_name='document',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='descuento'),
        ),
        migrations.AlterField(
            model_name='document',
            name='note',
            field=models.CharField(blank=True, max_length=500, verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.IntegerField(editable=False, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='document',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='impuesto'),
        ),
        migrations.AlterField(
            model_name='document',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=32, null=True, verbose_name='total'),
        ),
    ]
