# Generated by Django 3.1.4 on 2021-01-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20210104_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='affect_cost',
            field=models.BooleanField(default=False, help_text='indica si el costo promedio de los artículos será calculado.', verbose_name='afecta el costo'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='generic_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('purchase', 'Compra'), ('purchase_order', 'Orden de compra'), ('quotation', 'Cotización'), ('inventory_input', 'Entrada de inventario'), ('inventory_output', 'Salida de inventario')], default='', help_text='tipo genérico al que pertenece.', max_length=20, verbose_name='tipo genérico'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documenttype',
            name='inventory',
            field=models.CharField(blank=True, choices=[('input', 'Entrada'), ('output', 'Salida')], help_text='indica de que forma será afectado el inventario de artículos cuando se use este tipo de documento.', max_length=10, verbose_name='inventario'),
        ),
        migrations.AddField(
            model_name='documenttype',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
    ]
