# Generated by Django 3.1.4 on 2021-01-05 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210105_1502'),
        ('document', '0004_auto_20210105_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenttype',
            name='tax_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxreceipt', verbose_name='comprobante fiscal'),
        ),
    ]
