# Generated by Django 3.1.4 on 2021-01-05 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210105_1502'),
        ('document', '0005_documenttype_tax_receipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='tax_receipt_number',
            field=models.OneToOneField(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.taxreceiptnumber', verbose_name='Número de comprobante fiscal'),
        ),
    ]
