# Generated by Django 3.1.4 on 2021-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0008_auto_20210106_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=700),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=700),
        ),
    ]
