# Generated by Django 3.1.4 on 2021-01-08 04:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0010_auto_20210107_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tasa de cambio'),
        ),
    ]
