# Generated by Django 3.1.4 on 2021-01-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210106_1432'),
        ('document', '0011_auto_20210108_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='transfer_warehouse',
            field=models.ForeignKey(blank=True, default=None, help_text='almacén a transferir.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_transfer_set', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(help_text='almacén del documento.', on_delete=django.db.models.deletion.CASCADE, to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='generic_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('purchase', 'Compra'), ('purchase_order', 'Orden de compra'), ('quotation', 'Cotización'), ('inventory_input', 'Entrada de inventario'), ('inventory_output', 'Salida de inventario'), ('transfer', 'Transferencia de inventario')], help_text='tipo genérico al que pertenece.', max_length=20, verbose_name='tipo genérico'),
        ),
    ]
