# Generated by Django 3.1.4 on 2021-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0016_auto_20210117_0159'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='document',
            name='unique_doctype_number',
        ),
        migrations.AddField(
            model_name='document',
            name='sequence',
            field=models.IntegerField(editable=False, null=True, verbose_name='secuencia'),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.CharField(blank=True, max_length=30, verbose_name='número'),
        ),
    ]
