# Generated by Django 3.1.4 on 2021-01-19 22:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('document', '0017_auto_20210119_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, editable=False, max_length=100, verbose_name='nombre de usuario')),
                ('content', models.CharField(max_length=200, verbose_name='contenido')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(fields=('doctype', 'sequence'), name='unique_document_doctype_sequence'),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='create_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentnote',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document', verbose_name='documento'),
        ),
    ]
