# Generated by Django 3.1.4 on 2021-01-19 22:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0018_auto_20210119_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentnote',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha'),
            preserve_default=False,
        ),
    ]
