# Generated by Django 3.1.4 on 2021-01-23 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_auto_20210106_1432'),
        ('document', '0022_auto_20210120_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='transfer_warehouse',
            field=models.ForeignKey(blank=True, default=None, help_text='almacén a transferir.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='document_transfer_set', to='warehouse.warehouse'),
        ),
        migrations.AlterField(
            model_name='document',
            name='warehouse',
            field=models.ForeignKey(help_text='almacén del documento.', on_delete=django.db.models.deletion.PROTECT, to='warehouse.warehouse'),
        ),
    ]
