# Generated by Django 3.1.4 on 2021-01-24 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0023_auto_20210123_0145'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documenttype',
            old_name='generic_type',
            new_name='generic',
        ),
    ]
