# Generated by Django 3.1.4 on 2021-01-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0024_auto_20210124_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='Indica si el documento ya fue impreso.', verbose_name='Se imprimió'),
        ),
    ]
