# Generated by Django 3.1.4 on 2021-01-03 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0003_auto_20210102_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='código ISO.', max_length=3, verbose_name='código')),
                ('symbol', models.CharField(help_text='símbolo de dinero.', max_length=10, verbose_name='símbolo')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='tasa')),
                ('is_default', models.BooleanField(default=False, editable=False, verbose_name='moneda predeterminada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'ordering': ['is_default', 'code'],
            },
        ),
    ]
