# Generated by Django 3.1.4 on 2021-01-04 16:39

from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(max_length=700)),
                ('code', models.CharField(help_text='código ISO.', max_length=3, verbose_name='código')),
                ('symbol', models.CharField(help_text='símbolo de dinero.', max_length=10, verbose_name='símbolo')),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('rate', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='tasa')),
                ('is_default', models.BooleanField(default=False, editable=False, verbose_name='moneda predeterminada')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'moneda',
                'verbose_name_plural': 'monedas',
                'ordering': ['is_default', 'code'],
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_currency'),
        ),
    ]
