# Generated by Django 3.1.4 on 2021-01-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(fields=('company', 'code'), name='unique_company_currency'),
        ),
    ]
