# Generated by Django 3.1.4 on 2021-01-06 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_auto_20210105_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taxreceipt',
            name='code',
            field=models.CharField(help_text='código del tipo de comprobante según la DGII.', max_length=2, verbose_name='código'),
        ),
    ]
