# Generated by Django 3.1.4 on 2021-01-14 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0014_auto_20210114_1701'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('finance', '0005_auto_20210106_1432'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, editable=False, max_length=700)),
                ('mode', models.CharField(choices=[('-', 'Débito'), ('+', 'Crédito')], max_length=1, verbose_name='modo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=22, validators=[django.core.validators.MinValueValidator(0)], verbose_name='monto')),
                ('concept', models.CharField(blank=True, max_length=200, verbose_name='concepto')),
                ('create_user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='document.document')),
            ],
            options={
                'verbose_name': 'transacción',
                'verbose_name_plural': 'transacciones',
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
    ]
