# Generated by Django 3.1.4 on 2021-01-15 13:08

from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_logo'),
        ('finance', '0007_transaction_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, editable=False, max_length=700)),
                ('codename', models.CharField(max_length=50, verbose_name='referencia')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('value', models.DecimalField(decimal_places=2, max_digits=22, verbose_name='valor')),
                ('value_type', models.CharField(choices=[('percent', 'Porcentaje'), ('fixed', 'Fijo')], default='percent', max_length=10, verbose_name='tipo de valor')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'impuesto',
                'verbose_name_plural': 'impuestos',
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
        migrations.AddConstraint(
            model_name='tax',
            constraint=models.UniqueConstraint(fields=('company', 'codename'), name='unique_tax_codename'),
        ),
    ]
