# Generated by Django 3.1.4 on 2021-01-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20210115_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='mode',
        ),
    ]
