# Generated by Django 3.1.4 on 2021-01-20 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_remove_transaction_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=22, verbose_name='monto'),
        ),
    ]
