# Generated by Django 3.1.4 on 2021-01-20 22:35

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0010_auto_20210120_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='fecha'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_rate',
            field=models.DecimalField(blank=True, decimal_places=4, default=1, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tasa de cambio'),
        ),
    ]
