# Generated by Django 3.1.4 on 2021-01-21 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0013_auto_20210121_0150'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='paymentmethod',
            name='unique_paymentmethod_name',
        ),
        migrations.AddConstraint(
            model_name='paymentmethod',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_paymentmethod_name'),
        ),
    ]
