# Generated by Django 3.1.4 on 2021-01-08 17:16

from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, editable=False, max_length=700)),
                ('name', models.CharField(max_length=70, unique=True, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='descripción')),
                ('url_name', models.CharField(max_length=100, unique=True)),
                ('icon', models.ImageField(upload_to='module/module/')),
                ('parent', models.ForeignKey(blank=True, help_text='módulo padre al cual pertenece.', null=True, on_delete=django.db.models.deletion.CASCADE, to='module.module')),
            ],
            options={
                'verbose_name': 'módulo',
                'verbose_name_plural': 'módulos',
                'ordering': ['url_name'],
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
    ]
