# Generated by Django 3.1.4 on 2021-01-14 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20210110_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='csscolor',
            field=models.CharField(default='var(--secondary)', max_length=20, verbose_name='color'),
        ),
    ]
