# Generated by Django 3.1.4 on 2021-01-14 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0004_module_csscolor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='csscolor',
            field=models.CharField(default='var(--secondary)', max_length=30, verbose_name='color'),
        ),
    ]
