# Generated by Django 3.1.4 on 2021-01-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0005_auto_20210114_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='csscolor',
        ),
        migrations.AddField(
            model_name='module',
            name='css_bgcolor',
            field=models.CharField(default='var(--dark)', max_length=30, verbose_name='color de fondo'),
        ),
        migrations.AddField(
            model_name='module',
            name='css_textcolor',
            field=models.CharField(default='var(--light)', max_length=30, verbose_name='color del texto'),
        ),
    ]
