# Generated by Django 3.1.4 on 2021-01-14 17:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0006_auto_20210114_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='css_bgcolor',
            field=colorfield.fields.ColorField(default='#404040', max_length=18, verbose_name='Color del fondo'),
        ),
        migrations.AlterField(
            model_name='module',
            name='css_textcolor',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18, verbose_name='Color del texto'),
        ),
    ]
