# Generated by Django 3.1.4 on 2021-01-04 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movement',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='movement',
            name='currency_rate',
        ),
    ]
