# Generated by Django 3.1.4 on 2021-01-02 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210102_0715'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemfamily',
            options={'verbose_name': 'familia', 'verbose_name_plural': 'familias'},
        ),
        migrations.AlterModelOptions(
            name='itemgroup',
            options={'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
        migrations.AddField(
            model_name='itemfamily',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='itemgroup',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='company.company'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='itemfamily',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_family'),
        ),
        migrations.AddConstraint(
            model_name='itemgroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_company_group'),
        ),
    ]
