# Generated by Django 3.1.4 on 2021-01-02 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
        ('inventory', '0002_auto_20210102_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='document.document'),
            preserve_default=False,
        ),
    ]
