# Generated by Django 3.1.4 on 2021-01-10 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20210106_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='family',
            field=models.ForeignKey(blank=True, help_text='Puede ser la marca del fabricante.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemfamily', verbose_name='familia'),
        ),
        migrations.AlterField(
            model_name='item',
            name='group',
            field=models.ForeignKey(blank=True, help_text='grupo de artículos al que pertenece.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.itemgroup', verbose_name='grupo'),
        ),
    ]
