# Generated by Django 3.1.4 on 2021-01-14 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20210110_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item', verbose_name='artículo'),
        ),
    ]
