# Generated by Django 3.1.4 on 2021-01-15 13:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_auto_20210115_1308'),
        ('inventory', '0006_auto_20210114_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.tax'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='tax',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=22, validators=[django.core.validators.MinValueValidator(0)], verbose_name='impuesto'),
        ),
    ]
