# Generated by Django 3.1.4 on 2021-01-17 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20210117_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='tax_already_included',
            field=models.BooleanField(default=False, help_text='Indica que el impuesto ya está incluido en el monto (precio) especificado, entonces se extraerá el impuesto del monto indicado (si aplica).', verbose_name='impuesto ya incluido'),
        ),
    ]
