# Generated by Django 3.1.4 on 2021-01-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_movement_tax_already_included'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_service',
            field=models.BooleanField(default=False, verbose_name='es un artículo de servicio'),
        ),
    ]
