# Generated by Django 3.1.4 on 2021-01-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20210127_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='available_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='disponible'),
        ),
    ]
