# Generated by Django 3.1.4 on 2021-01-10 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0003_auto_20210106_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '', 'verbose_name_plural': ''},
        ),
    ]
