# Generated by Django 3.1.4 on 2021-01-11 02:50

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import unoletutils.libs.text


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_company_logo'),
        ('person', '0004_auto_20210110_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdentificationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.CharField(blank=True, editable=False, max_length=700)),
                ('name', models.CharField(max_length=50, verbose_name='nombre')),
                ('characters', models.CharField(default='0123456789', help_text='Indique los caracteres que desea permitir o prohibir.', max_length=500, verbose_name='caracteres permitidos')),
                ('mode', models.CharField(blank=True, choices=[('allowed', 'Permitir'), ('not_allowed', 'Prohibir')], default='allowed', max_length=20, verbose_name='modo')),
                ('max_length', models.IntegerField(blank=True, default=11, help_text='Longitud máxima permitida.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Longitud máxima')),
                ('min_length', models.IntegerField(blank=True, default=11, help_text='Longitud mínima permitida.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Longitud mínima')),
            ],
            options={
                'verbose_name': 'tipo de identificación',
                'verbose_name_plural': 'tipos de identificaciones',
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'persona', 'verbose_name_plural': 'personas'},
        ),
        migrations.AddField(
            model_name='person',
            name='business_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='nombre comercial'),
        ),
        migrations.AddField(
            model_name='person',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.person', verbose_name='persona de contacto'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='activo'),
        ),
        migrations.AddField(
            model_name='person',
            name='is_supplier',
            field=models.BooleanField(default=False, help_text='puede indicar si esta persona también es un suplidor.', verbose_name='es suplidor'),
        ),
        migrations.AddField(
            model_name='person',
            name='name',
            field=models.CharField(default='nombre 1', max_length=100, verbose_name='nombre'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='person',
            constraint=models.UniqueConstraint(fields=('company', 'identification'), name='unique_person_identification'),
        ),
        migrations.AddField(
            model_name='identificationtype',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa'),
        ),
        migrations.AddConstraint(
            model_name='identificationtype',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_identificationtype_name'),
        ),
    ]
