# Generated by Django 3.1.4 on 2021-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0006_person_identification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='correo electrónico'),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='teléfono'),
        ),
    ]
