# Generated by Django 3.1.4 on 2021-01-11 12:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0007_auto_20210111_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Límite de crédito permitido para esta persona.', max_digits=22, validators=[django.core.validators.MinValueValidator(0)], verbose_name='límite de crédito'),
        ),
        migrations.AddField(
            model_name='person',
            name='credit_limit_days',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='tiempo límite de crédito en días'),
        ),
    ]
