# Generated by Django 3.1.4 on 2021-01-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0008_auto_20210111_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='identification_type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='person.identificationtype', verbose_name='Tipo de identificación'),
        ),
    ]
