# Generated by Django 3.1.4 on 2021-01-02 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalwarehouse',
            name='company',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='empresa a la que pertenece este almacén.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='company.company'),
        ),
    ]
