# Generated by Django 3.1.4 on 2021-01-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0005_auto_20210106_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcompany',
            name='logo',
            field=models.TextField(blank=True, max_length=100, verbose_name='logo'),
        ),
    ]
