# Generated by Django 3.1.4 on 2021-01-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0008_auto_20210119_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaldocument',
            name='sequence',
            field=models.IntegerField(editable=False, null=True, verbose_name='secuencia'),
        ),
    ]
