# Generated by Django 3.1.4 on 2021-01-24 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0009_auto_20210124_2044'),
        ('audit', '0011_auto_20210120_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaldocumenttype',
            old_name='generic_type',
            new_name='generic',
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='identification_type',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='person.identificationtype', verbose_name='Tipo de identificación'),
        ),
    ]
