# Generated by Django 3.1.4 on 2021-01-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0013_historicalitem_is_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalitem',
            name='available_json',
            field=models.JSONField(blank=True, null=True, verbose_name='disponible'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='codename',
            field=models.CharField(help_text='Puede ser el módelo, serie, identificador, etc. Esta referencia debería ser única pero puede tener artículos con la misma referencia si así lo desea.', max_length=30, verbose_name='referencia'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='description',
            field=models.CharField(blank=True, help_text='breve descripción y características del artículo.', max_length=500, verbose_name='descripción'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='name',
            field=models.CharField(help_text='nombre del artículo. Este será mostrado en los documentos.', max_length=70, verbose_name='nombre'),
        ),
    ]
