# Generated by Django 3.1.4 on 2021-01-28 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0014_auto_20210127_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaldocument',
            name='is_printed',
            field=models.BooleanField(default=False, help_text='Indica si el documento ya fue impreso.', verbose_name='Se imprimió'),
        ),
        migrations.AlterField(
            model_name='historicalitem',
            name='available_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='disponible'),
        ),
    ]
