# Generated by Django 3.1.4 on 2021-01-04 16:39

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import unoletutils.libs.text


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre de la empresa para el público.', max_length=100, verbose_name='nombre')),
                ('business_name', models.CharField(help_text='nombre legal registrado de la empresa.', max_length=100, verbose_name='Razón social')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['site', 'name'],
            },
            bases=(models.Model, unoletutils.libs.text.Text),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(editable=False, max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='descripción')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'permiso por empresa',
                'verbose_name_plural': 'permisos por empresa',
                'ordering': ['company', 'codename', 'name'],
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
        migrations.CreateModel(
            name='CompanyPermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company', verbose_name='Empresa')),
                ('permissions', models.ManyToManyField(to='company.CompanyPermission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'grupo de permiso por empresa',
                'verbose_name_plural': 'grupos permisos por empresa',
                'ordering': ['company', 'codename', 'name'],
            },
            bases=(models.Model, unoletutils.libs.text.Text),
        ),
    ]
