# Generated by Django 3.1.4 on 2020-12-28 23:13

import django.contrib.sites.managers
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import unoletutils.libs.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='nombre de la empresa para el público.', max_length=100, verbose_name='nombre')),
                ('business_name', models.CharField(help_text='nombre legal registrado de la empresa.', max_length=100, verbose_name='Razón social')),
                ('is_active', models.BooleanField(default=True, verbose_name='activo')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site')),
            ],
            options={
                'verbose_name': 'empresa',
                'verbose_name_plural': 'empresas',
                'ordering': ['site', 'name'],
            },
            bases=(models.Model, unoletutils.libs.utils.ModelBase),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('on_site', django.contrib.sites.managers.CurrentSiteManager()),
            ],
        ),
    ]
