# Generated by Django 3.1.4 on 2021-01-04 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('company', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_users',
            field=models.ManyToManyField(blank=True, related_name='admin_users_company_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='create_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='create_user_company_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='sites.site'),
        ),
        migrations.AddField(
            model_name='company',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='companypermissiongroup',
            constraint=models.UniqueConstraint(fields=('company', 'codename'), name='unique_companypermissiongroup_codename'),
        ),
        migrations.AddConstraint(
            model_name='companypermissiongroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_companypermissiongroup_name'),
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(fields=('company', 'codename'), name='unique_companypermission_codename'),
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_companypermission_name'),
        ),
    ]
