# Generated by Django 3.1.4 on 2021-01-08 04:07

from django.db import migrations, models
import unoletutils.libs.utils


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20210104_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to=unoletutils.libs.utils.upload_file_on_site, verbose_name='logo'),
        ),
    ]
