# Generated by Django 3.1.4 on 2021-01-04 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_auto_20210102_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='descripción')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
            ],
            options={
                'verbose_name': 'permiso por empresa',
                'verbose_name_plural': 'permisos por empresa',
                'ordering': ['company', 'codename', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPermissionGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.CharField(max_length=50, verbose_name='código')),
                ('name', models.CharField(max_length=100, verbose_name='nombre')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.company')),
                ('permissions', models.ManyToManyField(to='company.CompanyPermission', verbose_name='permisos')),
            ],
            options={
                'verbose_name': 'grupo de permiso por empresa',
                'verbose_name_plural': 'grupos permisos por empresa',
                'ordering': ['company', 'codename', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='companypermissiongroup',
            constraint=models.UniqueConstraint(fields=('company', 'codename'), name='unique_companypermissiongroup_codename'),
        ),
        migrations.AddConstraint(
            model_name='companypermissiongroup',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_companypermissiongroup_name'),
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(fields=('company', 'codename'), name='unique_companypermission_codename'),
        ),
        migrations.AddConstraint(
            model_name='companypermission',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_companypermission_name'),
        ),
    ]
