# Generated by Django 3.1.4 on 2021-01-04 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20210104_0015'),
        ('user', '0002_auto_20210104_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_groups',
            field=models.ManyToManyField(blank=True, to='company.CompanyPermissionGroup', verbose_name='grupo de permisos por empresa'),
        ),
        migrations.AlterField(
            model_name='user',
            name='company_permissions',
            field=models.ManyToManyField(blank=True, to='company.CompanyPermission', verbose_name='permisos por empresa'),
        ),
    ]
